export { default as cliTemplate } from "@trapar-waves/cli-template/package.json";
export { default as llmTemplate } from "@trapar-waves/llm-template/package.json";
export { default as reactAntdPro } from "@trapar-waves/react-antd-pro/package.json";
export { default as reactMantineTailwind } from "@trapar-waves/react-mantine-tailwind/package.json";
export { default as reactTailwind } from "@trapar-waves/react-tailwind/package.json";
export { default as reactTanstack } from "@trapar-waves/react-tanstack/package.json";
export { default as reactThreeMaplibre } from "@trapar-waves/react-three-maplibre/package.json";
export { default as reactVisglMaplibre } from "@trapar-waves/react-visgl-maplibre/package.json";
export { default as vueTailwind } from "@trapar-waves/vue-tailwind/package.json";
